trigger: none

pool:
  name: PoolAirtel

steps:
- task: NodeTool@0
  displayName: "Install Node.js"
  inputs:
    versionSpec: "18.x"
- task: Npm@1
  displayName: NPM Install
  inputs:
    command: 'install'
- task: Npm@1
  displayName: NPM run build
  inputs:
    command: 'custom'
    customCommand: 'npm run build'