trigger: none

pool:
  name: PoolAirtel

steps:
- task: NodeTool@0
  displayName: "Use Node 16"
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'
    checkLatest: true

# Just to test
- task: PowerShell@2
  displayName: "Hello"
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Hello World"

# NPM Install (Correct Folder)
- task: PowerShell@2
  displayName: "NPM Install"
  inputs:
    targetType: 'inline'
    script: |
      npm install
    workingDirectory: '$(Build.SourcesDirectory)'   # THIS IS YOUR PROJECT ROOT

# NPM Build
- task: PowerShell@2
  displayName: "NPM Build"
  inputs:
    targetType: 'inline'
    script: |
      npm run build
    workingDirectory: '$(Build.SourcesDirectory)'
