trigger: none

pool:
  name: PoolAirtel

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'
    checkLatest: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
- task: PowerShell@2
  inputs:
    filePath: 'D:\Pipeline\Agent\vsts-agent-win-x64-4.259.0\ReactTodoUIMonolith'
- task: PowerShell@2
  displayName: "NPM Install"
  inputs:
    targetType: 'inline'
    script: |
      npm install
    workingDirectory: '$(Build.SourcesDirectory)' 