trigger: none

pool:
  name: PoolAirtel

steps:
- checkout: self   # <-- MOST IMPORTANT FIX

- task: NodeTool@0
  displayName: "Use Node 16"
  inputs:
    versionSpec: '16.x'

- task: PowerShell@2
  displayName: "NPM Install"
  inputs:
    targetType: 'inline'
    script: |
      npm install
    workingDirectory: '$(Build.SourcesDirectory)/ReactTodoUIMonolith'

- task: PowerShell@2
  displayName: "NPM Build"
  inputs:
    targetType: 'inline'
    script: |
      npm run build
    workingDirectory: '$(Build.SourcesDirectory)/ReactTodoUIMonolith'
