trigger: none

pool:
  name: PoolAirtel

steps:
- task: PowerShell@2
  displayName: npm install
  inputs:
    targetType: inline
    script: |
      npm install

- task: PowerShell@2
  displayName: npm run build
  inputs:
    targetType: inline
    script: |
      npm run build
