trigger: none

pool:
  name: PoolAirtel

steps:
- task: NodeTool@0
  displayName: Install Node.js
  inputs:
    versionSpec: '18.x'

- task: PowerShell@2
  displayName: npm install
  inputs:
    targetType: inline
    script: |
      cd frontend
      npm install

- task: PowerShell@2
  displayName: npm run build
  inputs:
    targetType: inline
    script: |
      cd frontend
      npm run build
